# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Kate Sevigny
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Kate Sevigny
description              : Kate Sevigny - Projects and CV 
baseurl                  : "fa25-portfolio-KateSevigny" # the subpath of your site, e.g. /blog/
url                      : "https://kate-sevigny.github.io" # the base hostname & protocol for your site
author                   : Kate Sevigny
email                    : kas573@cornell.edu

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

